In [152]:
import numpy as np


## CONVERTING A LIST INTO ARRAY

In [153]:
lst = [1,2,3,4,5]
print(type(lst))

arr1 =np.array(lst)
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


## ARANGE FUNCTION

In [154]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## SIZE FUNCTION

In [155]:
lst = [[1,2,3],[4,5,6],[6,7,8],[9,10,11]]

arr2 =np.array(lst)

print("Total : " ,arr2.size)
# arr.size(arr,0)
print("Total rows : " ,np.size(arr2,0))
print("Total col: ",np.size(arr2,1))

arr2

Total :  12
Total rows :  4
Total col:  3


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

## SHAPE FUNCTION 

In [156]:
np.shape(arr1)
arr1.shape

(5,)

In [157]:
arr2.shape

(4, 3)

## DTYPE FUNCTION

In [158]:
print(arr1.dtype)
print(arr2.dtype)

int32
int32


## ndim function

In [159]:
arr2.ndim

2

## ZEROES FUNCTIONS

In [160]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## ONES FUNCTION

In [161]:
np.ones(2)

array([1., 1.])

## eye function
np.eye(n , m, k , dtype)

In [162]:
np.eye(5, dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

## empty function

In [163]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## RANDOM FUNCTIONS


In [164]:
np.random.rand(10)

array([0.35390507, 0.49263593, 0.91330145, 0.76582638, 0.97364827,
       0.40236064, 0.55277195, 0.30636063, 0.58661997, 0.27492011])

In [165]:
np.random.randint(1,10,5)

array([2, 1, 6, 5, 2])

In [166]:
np.random.randn(10)

array([ 0.62524497, -0.16051336, -0.76883635, -0.23003072,  0.74505627,
        1.97611078, -1.24412333, -0.62641691, -0.80376609, -2.41908317])

## reshape function

In [167]:
arr3 = np.random.randint(1,11,(4,4))
np.reshape(arr3, (2,8))

array([[5, 4, 1, 1, 1, 1, 3, 3],
       [8, 1, 6, 1, 2, 5, 2, 3]])

## linspace funtion

In [168]:
np.linspace(1,10,9)

array([ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875,
       10.   ])

## flatten function

In [169]:
arr = arr3.flatten()


In [170]:
arr.shape

(16,)

## copy function

In [171]:
arr1 = np.random.randint(1,10,10)
print(arr1, id(arr1))

arr2 = arr1
print(arr2, id(arr2))

print("-"*50)
arr1 = np.copy(arr2)

print(arr1, id(arr1))
print(arr2, id(arr2))

[3 5 9 1 7 1 5 2 6 2] 2830293606704
[3 5 9 1 7 1 5 2 6 2] 2830293606704
--------------------------------------------------
[3 5 9 1 7 1 5 2 6 2] 2830293528336
[3 5 9 1 7 1 5 2 6 2] 2830293606704


## SEED FUNCTION

In [172]:
np.random.seed(42)

np.random.randint(1,10,10)

array([7, 4, 8, 5, 7, 3, 7, 8, 5, 4])

## MATHEMATICAL OPERATIONS

ADDITION

In [173]:
np.random.seed(3)

arr = np.random.randint(1,10,(3,5))
print(arr)
print(arr +1)

[[9 4 9 9 1]
 [6 4 6 8 7]
 [1 5 8 9 2]]
[[10  5 10 10  2]
 [ 7  5  7  9  8]
 [ 2  6  9 10  3]]


In [174]:
np.random.seed(3)

arr1 = np.random.randint(1,10,(3,5))

arr2 = np.random.randint(1,10,(3,5))
print(arr1)
print("-"*50)
print(arr2)
print("-"*50)
print(arr1+ arr2)

[[9 4 9 9 1]
 [6 4 6 8 7]
 [1 5 8 9 2]]
--------------------------------------------------
[[7 3 3 2 4]
 [6 9 2 9 8]
 [9 2 1 6 5]]
--------------------------------------------------
[[16  7 12 11  5]
 [12 13  8 17 15]
 [10  7  9 15  7]]


subtraction

In [175]:
np.random.seed(3)

arr1 = np.random.randint(1,10,(3,5))

print(arr1)
print("-"*50)
print(arr1-1)

[[9 4 9 9 1]
 [6 4 6 8 7]
 [1 5 8 9 2]]
--------------------------------------------------
[[8 3 8 8 0]
 [5 3 5 7 6]
 [0 4 7 8 1]]


##  MATRIX MULTPLICATION


In [177]:
np.random.seed(3)

arr1 = np.random.randint(1,10,(2,2))
arr2 = np.random.randint(1,10,(2,2))

print(arr1)
print("-"*50)
print(arr2)
print("-"*50)
print(arr1@arr2)

[[9 4]
 [9 9]]
--------------------------------------------------
[[1 6]
 [4 6]]
--------------------------------------------------
[[ 25  78]
 [ 45 108]]


## MEAN , vARINACE AND STANDARD DEVIATION


In [184]:
np.random.seed(3)
arr = np.random.randint(1,10,10)
print(arr)

print(arr.mean())
print(arr.var())
print(arr.std())

[9 4 9 9 1 6 4 6 8 7]
6.3
6.410000000000001
2.5317977802344327


## FILTERING

In [186]:
np.random.seed(3)
arr = np.random.randint(1,10,10)
print(arr)

print(arr[arr>5])

[9 4 9 9 1 6 4 6 8 7]
[9 9 9 6 6 8 7]


##  MERGING ARRAYS
CANCATENATE

In [190]:
np.random.seed(3)
arr1 = np.random.randint(1,10,(2,4))
arr2 = np.random.randint(1,10,(2,4))

print(np.concatenate((arr1, arr2)))

[[9 4 9 9]
 [1 6 4 6]
 [8 7 1 5]
 [8 9 2 7]]
