In [78]:
import numpy as np


## CONVERTING A LIST INTO ARRAY

In [79]:
lst = [1,2,3,4,5]
print(type(lst))

arr1 =np.array(lst)
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


## ARANGE FUNCTION

In [80]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## SIZE FUNCTION

In [81]:
lst = [[1,2,3],[4,5,6],[6,7,8],[9,10,11]]

arr2 =np.array(lst)

print("Total : " ,arr2.size)
# arr.size(arr,0)
print("Total rows : " ,np.size(arr2,0))
print("Total col: ",np.size(arr2,1))

arr2

Total :  12
Total rows :  4
Total col:  3


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

## SHAPE FUNCTION 

In [82]:
np.shape(arr1)
arr1.shape

(5,)

In [83]:
arr2.shape

(4, 3)

## DTYPE FUNCTION

In [84]:
print(arr1.dtype)
print(arr2.dtype)

int32
int32


## ndim function

In [85]:
arr2.ndim

2

## ZEROES FUNCTIONS

In [86]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## ONES FUNCTION

In [87]:
np.ones(2)

array([1., 1.])

## eye function
np.eye(n , m, k , dtype)

In [88]:
np.eye(5, dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

## empty function

In [89]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## RANDOM FUNCTIONS


In [90]:
np.random.rand(10)

array([0.35003122, 0.58770518, 0.6716108 , 0.79937382, 0.32448601,
       0.16819377, 0.88613673, 0.90284142, 0.2160726 , 0.90480978])

In [91]:
np.random.randint(1,10,5)

array([4, 7, 9, 4, 6])

In [92]:
np.random.randn(10)

array([ 1.19964537,  2.0414817 ,  0.82176963, -1.72516674,  1.1124437 ,
       -0.3056044 ,  0.0544323 , -1.72209275, -0.29567379, -0.33228261])